version: 2.1

orbs:
  win: circleci/windows@4.1.1

jobs:
  make:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command: 
            sudo apt-get install build-essential libboost-all-dev xsltproc autorevision
            && make -C src && make -C src/examples && make -C src/test && ./src/test/test

  cmake:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command:
            sudo apt-get install build-essential libboost-all-dev xsltproc autorevision
            && mkdir build && cd build && cmake .. && make -j4
 
  cmake-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          command:
            sudo apt-get install build-essential libboost-all-dev xsltproc autorevision
            && mkdir build-dev && cd build-dev && cmake -DDEVELOPER=1 .. && make -j4 && ctest -V

  vstudio:
    executor: win/default
    steps:
      - checkout
      - run:
          name: boost 
          command: |
            curl https://boostorg.jfrog.io/artifactory/main/release/1.79.0/source/boost_1_79_0.7z -O boost.7z
            7z x boost.7z -oc:\Users\circleci\project\src
            cd c:\Users\circleci\project\src\boost_1_79_0
            bootstrap
            .\b2 -j 2
      - run: msbuild.exe C:\Users\circleci\project\src\msvc2017\scxmlcc.sln /verbosity:minimal /p:Platform="Win32"
          

workflows:
  build:
    jobs:
      - vstudio
      - make
      - cmake
      - cmake-dev
