#! /bin/bash
set -x
version=`git diff HEAD^..HEAD -- "$(git rev-parse --show-toplevel)"/src/version.h | grep '^\+.*VERSION' | sed -s 's/[^0-9\.]//g'`

if [ "$version" != "" ]; then
    git tag -a "v$version" -m "`git log -1 --format=%s`"
    echo "Created a new tag, v$version"
fi

