/* Generated by autorevision - do not hand-hack! */
#ifndef AUTOREVISION_H
#define AUTOREVISION_H

#define VCS_TYPE		"git"
#define VCS_BASENAME	"scxmlcc"
#define VCS_NUM			36
#define VCS_DATE		"2015-03-20T12:02:34+0100"
#define VCS_BRANCH		"master"
#define VCS_TAG			""
#define VCS_TICK		36

#define VCS_FULL_HASH		"fc42a023e937e11e8d61c0120c9b44a54f927a8d"
#define VCS_SHORT_HASH		"fc42a02"

#define VCS_WC_MODIFIED		1

#endif

/* end */
